In [1]:
import pandas as pd

In [2]:
sp500 = pd.read_csv("Datasets/S&P500.csv")
sp500.head()

   Date  Returns
0  2008   -38.49
1  2009    23.45
2  2010    12.78
3  2011     0.00
4  2012    13.41

In [3]:
gdp = pd.read_csv("Datasets/WorldBank_GDP.csv")
gdp.head()

    Country Name Country Code     Indicator Name  Year           GDP
0          China          CHN  GDP (current US$)  2010  6.087160e+12
1        Germany          DEU  GDP (current US$)  2010  3.417090e+12
2          Japan          JPN  GDP (current US$)  2010  5.700100e+12
3  United States          USA  GDP (current US$)  2010  1.499210e+13
4          China          CHN  GDP (current US$)  2011  7.551500e+12

### merge_ordered()
1. Best for time series and ordered data
2. By default it does outer join

In [6]:
gdp_sp500 = pd.merge_ordered(gdp, sp500, left_on='Year', right_on='Date', how='left')
gdp_sp500

,Country Name,Country Code,Indicator Name,Year,GDP,Date,Returns
0,China,CHN,GDP (current US$),2010,6.087160e+12,2010.0,12.78
1,Germany,DEU,GDP (current US$),2010,3.417090e+12,2010.0,12.78
2,Japan,JPN,GDP (current US$),2010,5.700100e+12,2010.0,12.78
3,United States,USA,GDP (current US$),2010,1.499210e+13,2010.0,12.78
4,China,CHN,GDP (current US$),2011,7.551500e+12,2011.0,0.00
5,Germany,DEU,GDP (current US$),2011,3.757700e+12,2011.0,0.00
6,Japan,JPN,GDP (current US$),2011,6.157460e+12,2011.0,0.00
7,United States,USA,GDP (current US$),2011,1.554260e+13,2011.0,0.00
8,China,CHN,GDP (current US$),2012,8.532230e+12,2012.0,13.41
9,Germany,DEU,GDP (current US$),2012,3.543980e+12,2012.0,13.41
10,Japan,JPN,GDP (current US$),2012,6.203210e+12,2012.0,13.41
11,United States,USA,GDP (current US$),2012,1.619700e+13,2012.0,13.41
12,China,CHN,GDP (current US$),2012,8.532230e+12,2012.0,13.41
13,Germany,DEU,GDP (current US$),2012,3.543980e+12,2012.0,13.41
14,Japan,JPN,GDP (current US$),2012,6.203210e+12,2012.0,13.41
15,United States,USA,GDP (current US$),2012,1.619700e+13,2012.0,13.41
16,China,CHN,GDP (current US$),2013,9.570410e+12,2013.0,29.60
17,Germany,DEU,GDP (current US$),2013,3.752510e+12,2013.0,29.60
18,Japan,JPN,GDP (current US$),2013,5.155720e+12,2013.0,29.60
19,United States,USA,GDP (current US$),2013,1.678480e+13,2013.0,29.60
20,China,CHN,GDP (current US$),2014,1.043850e+13,2014.0,11.39
21,Germany,DEU,GDP (current US$),2014,3.898730e+12,2014.0,11.39
22,Japan,JPN,GDP (current US$),2014,4.850410e+12,2014.0,11.39
23,United States,USA,GDP (current US$),2014,1.752170e+13,2014.0,11.39
24,China,CHN,GDP (current US$),2015,1.101550e+13,2015.0,-0.73
25,Germany,DEU,GDP (current US$),2015,3.381390e+12,2015.0,-0.73
26,Japan,JPN,GDP (current US$),2015,4.389480e+12,2015.0,-0.73
27,United States,USA,GDP (current US$),2015,1.821930e+13,2015.0,-0.73
28,China,CHN,GDP (current US$),2016,1.113790e+13,2016.0,9.54
29,Germany,DEU,GDP (current US$),2016,3.495160e+12,2016.0,9.54
30,Japan,JPN,GDP (current US$),2016,4.926670e+12,2016.0,9.54
31,United States,USA,GDP (current US$),2016,1.870720e+13,2016.0,9.54
32,China,CHN,GDP (current US$),2017,1.214350e+13,2017.0,19.42
33,Germany,DEU,GDP (current US$),2017,3.693200e+12,2017.0,19.42
34,Japan,JPN,GDP (current US$),2017,4.859950e+12,2017.0,19.42
35,United States,USA,GDP (current US$),2017,1.948540e+13,2017.0,19.42
36,China,CHN,GDP (current US$),2018,1.360820e+13,NaN,NaN
37,Germany,DEU,GDP (current US$),2018,3.996760e+12,NaN,NaN
38,Japan,JPN,GDP (current US$),2018,4.970920e+12,NaN,NaN
39,United States,USA,GDP (current US$),2018,2.049410e+13,NaN,NaN

#### fill_method 
ffill - fills value of the row above

In [ ]:
gdp_sp500 = pd.merge_ordered(gdp, sp500, left_on='Year', right_on='Date', how='left', fill_method ="ffill")
gdp_sp500